### ISSUE TITLE
[Bug] latest version not remembering window position

### ISSUE THREAD

**Issue by Incognito-100** [SpikeHD/Dorion#272]
**Describe the bug**
new update doesn't remember window size and position

**To Reproduce**
Steps to reproduce the behavior: open apps resize or move it then close it down and reopen

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: 6.3.0
 - Extra Client Mods/Plugins: None

**Comment by SpikeHD** [comment]
Does it work with `v6.2.0`?

**Comment by kajoken** [comment]
Came here to say the same. After the update to 6.3.0 that old bug is back. Worst thing is, I can't downgrade to 6.2.0 since it forces the update on us. 6.2.0 worked fine, now it's back to it's little starting window every time.

**Comment by SpikeHD** [comment]
It only forces the update on you only if you have autoupdate enabled, if it's a problem you can disable it on v6.3.0 before going back to v6.2.0

As for root cause, I honestly couldn't find it at a glance, I [moved some old code around](https://github.com/SpikeHD/Dorion/commit/f58e600965da1b61c8f29e336818c4d9c920d8cd) but there is still the [saving](https://github.com/SpikeHD/Dorion/blob/4ffd7e50a0404a42fac145a06f4564a1be2b6836/src-tauri/src/main.rs#L236) and [restoration](https://github.com/SpikeHD/Dorion/blob/4ffd7e50a0404a42fac145a06f4564a1be2b6836/src-tauri/src/functionality/configure/mod.rs#L62) of window state, at roughly the same spot in the load/window destroy cycle they always were. I'll do some testing and maybe rollback the window state plugin if I have to

**Comment by kajoken** [comment]
Thanks for the heads up. I totally forgot I had auto update active. Deactivated, went back to 6.2.0 and it works fine again.

**Comment by SpikeHD** [comment]
Looks like this is caused by a regression in one of the libraries Dorion uses (see https://github.com/tauri-apps/tauri/issues/11740), that comes from having both decorations off and window shadows enabled, which is mighty unlucky since Dorion does in fact do both, lol.

Once `tao` is updated (see https://github.com/tauri-apps/tao/pull/1010) and `tauri` is updated to use that new version , I will release a patch 👍 

For now, if it helps, Dorion will still remember if it were maximized and will re-maximize itself, it just won't properly apply size and position. This is also only a Windows issue, and worked fine on my M1 Macbook when testing.

**Comment by Incognito-100** [comment]
good to know the fix seem easy

**Comment by SpikeHD** [comment]
This *should* be fixed as of bcfbb291217b860143a2b9d849a1a3b1c5fe8313, try an actions build (which you can get via the "Bleeding Edge builds" dropdown in the READMEs "Downloads" section) and if it's still busted, let me know here 👍

**Comment by kajoken** [comment]
Not fixed. Just tried the "bleeding edge build" and window position still gets reset every start.

**Comment by SpikeHD** [comment]
Ok [this time for sure](https://github.com/tauri-apps/tauri/issues/12168)

**Comment by kajoken** [comment]
Can confirm. The bleeding edge build works now on my side. Tried it on several monitors, Fullscreen, window snapped and just windowed and all positions were saved. Thank you for the fix. :)
